name: Generate Babele light index

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: generate-light-index-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate labels.json / titles.json
        env:
          SCRIPT_PATH: tools/generate-light-index.mjs
          INPUT_DIRS: |
            translations/zh-cn
        run: |
          set -euo pipefail
          if [ ! -f "$SCRIPT_PATH" ]; then
            echo "Script not found: $SCRIPT_PATH"
            exit 1
          fi
          while IFS= read -r dir; do
            [ -z "$dir" ] && continue
            if [ ! -d "$dir" ]; then
              echo "Input dir not found: $dir"
              exit 1
            fi
            node "$SCRIPT_PATH" --input "$dir" --include-folders
          done <<< "$INPUT_DIRS"

      - name: Commit changes (if any)
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: regenerate light index"
          git push

